version: '3'
services:
  db:
    image: 'postgres:10'
    ports: 
      - '5433:5433'
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6380:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/blog-posts'
      - '/blog-posts/tmp' # don't mount tmp directory
    

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}"
    volumes:
      - .:/blog-posts
    ports:
      - "3000:3000"
    depends_on:
      - 'db'
      - 'redis'
    tty: true
    links: 
      - db
    stdin_open: true

volumes:
  db: 
  redis: